// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.833
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Home() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"bg-white shadow-md rounded-lg p-6\"><h2 class=\"text-2xl font-bold mb-4\">Добро пожаловать в EZLine</h2><p class=\"text-gray-600 mb-4\">Система управления производственной линией</p><div class=\"grid grid-cols-1 md:grid-cols-2 gap-6 mt-8\"><div class=\"bg-gray-100 p-4 rounded-lg shadow\"><h3 class=\"text-xl font-semibold mb-2\">Производственные задания</h3><p class=\"mb-4\">Просмотр и выполнение заданий для вашей производственной линии.</p><a href=\"/tasks\" class=\"bg-green-500 hover:bg-green-600 text-white px-4 py-2 rounded\">Перейти к заданиям</a></div><div class=\"bg-gray-100 p-4 rounded-lg shadow\"><h3 class=\"text-xl font-semibold mb-2\">Сканирование</h3><p class=\"mb-4\">Сканирование и валидация кодов маркировки продукции.</p><button disabled class=\"bg-gray-400 text-white px-4 py-2 rounded\">Выберите задание для начала сканирования</button></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
